# Media Stack - Jellyfin, Overseerr, Jellystat, Wizarr, Dispatcharr
# Media server and request management

name: media

########################### NETWORKS
networks:
#  default:
#    driver: bridge
#  socket_proxy:
#    name: socket_proxy
  t3_proxy:
     external: true
  iot_macvlan:
     external: true


include:
  ########################### SERVICES

  - jellyfin.yaml
  - dispatcharr.yaml
  - seerr.yaml
  - jellystat.yaml
  - wizarr.yaml


