# Homarr - Customizable homepage/dashboard for the whole family
# https://homarr.dev

include:
  - homarr.yaml

networks:
  t3_proxy:
    external: true

volumes:
  homarr_configs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/fast/appdata/homarr/configs
  homarr_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/fast/appdata/homarr/data
  homarr_icons:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/fast/appdata/homarr/icons
  homarr_appdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/fast/appdata/homarr/appdata
