# Arrs Stack - Media automation suite
# SABnzbd, qBittorrent, Prowlarr, Radarr, Sonarr, Lidarr, Readarr, Bazarr

name: arrs

########################### NETWORKS
networks:
#  default:
#    driver: bridge
#  socket_proxy:
#    name: socket_proxy
  t3_proxy:
     external: true
  # automation:
  #   name: automation
  #   driver: bridge
  #   ipam:
  #     config:
  #       - subnet: 192.168.85.0/24


include:
  ########################### SERVICES

  - sabnzbd.yaml
  - qbittorrent.yaml
  - prowlarr.yaml
  - radarr.yaml
  - sonarr.yaml
  - lidarr.yaml
  - readarr.yaml
  - bazarr.yaml
  - flaresolverr.yaml
  - autobrr.yaml
  - janitorr.yaml
  - blockbusterr.yaml
#  - boxarr.yaml  # Commented out - image not published to Docker Hub yet (needs to be built from source)
#  - beets.yaml


